### ISSUE TITLE
是否因为与其他模块冲突的原因

### ISSUE THREAD

**Issue by zhangyilibecnu** [Daniel-KM/Omeka-S-module-AdvancedSearch#12]
Laminas\ServiceManager\Exception\InvalidServiceException: Plugin manager "Laminas\ServiceManager\AbstractPluginManager" expected an instance of type "Search\FormAdapter\FormAdapterInterface", but "AdvancedSearch\FormAdapter\MainFormAdapter"…

**Comment by Daniel-KM** [comment]
Fixed in 3.4.31.
