### ISSUE TITLE
Suggestion not working with Solr

### ISSUE THREAD

**Issue by snowwtarie** [Daniel-KM/Omeka-S-module-AdvancedSearch#17]
Hello,

I found a bug while setting up auto-suggestion with a Solr core. I don't know if it's related to Solr >= 9 but the returned JSON is wrongly transformed in **search.js line 192**. 

It should be `const searchString = Object.keys(answer)[0];` instead of `const searchString = answer[Object.keys(answer)[0]];`

I have not investigated this issue any further because this change fixed it but a quick patch could be
```js
const searchString = answer[Object.keys(answer)[0]] instanceof String ? answer[Object.keys(answer)[0]] : Object.keys(answer)[0];

if (!Object.keys(answer[searchString]).find((key) => 'suggestions' === key)) {
    return {};
}

// Rest of the script
```

**Comment by Daniel-KM** [comment]
Ok, thanks, i included your fix to manage various versions of solr.
