### ISSUE TITLE
Duplicating unique ID

### ISSUE THREAD

**Issue by allanaaa** [Daniel-KM/Omeka-S-module-AdvancedSearch#6]
An issue was identified where a core Omeka S ID is being duplicated in a page block introduced by this module:

https://forum.omeka.org/t/css-changes-to-search-boxes-and-sorting-options/17627

You will need to change how you render the search form so that it doesn't duplicate IDs.

**Comment by Daniel-KM** [comment]
Hi, But the omeka form id is "search-form" and my block uses "form-search". So not sure if it is the issue.
